---

image: clojure:openjdk-16-tools-deps-slim-buster

# Due to a GitLab bug we need to extend the cache for each job
# rather than rely on a top level cache with a per job policy.
# https://gitlab.com/gitlab-org/gitlab-runner/issues/2838

.cache:
  cache:
    key: "${CI_COMMIT_REF_NAME}"
    paths:
      - .cpcache/
      - /root/.m2/
    policy: pull-push

stages:
  - test
  - package
  - publish

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

test:
  extends: .cache
  stage: test
  script:
    - clojure -Sdeps "${DEPS}" -M:test -m kaocha.runner
  cache:
    policy: pull

package:
  extends: .cache
  stage: package
  script:
    - clojure -X:uberjar
  cache:
    policy: pull
  artifacts:
    paths:
      - app.jar
    expire_in: 1 day

publish:
  extends: .cache
  stage: publish
  dependencies:
    - package
  image: docker:latest
  variables:
    DOCKER_CONFIG: /root/.docker
    IMAGE: $DOCKER_REGISTRY/$CI_PROJECT_PATH
    JVM_TAG: openjdk-16-tools-deps-slim-buster
    JMX_EXPORTER_VERSION: 0.15.0
  before_script:
    - mkdir -p $DOCKER_CONFIG
    - echo "$DOCKER_AUTH_CONFIG" > $DOCKER_CONFIG/config.json
    - export TAG=$(echo -en ${CI_COMMIT_REF_NAME#rel/} | tr -c '[:alnum:]_.-' '-')
  script:
    - docker build --pull --cache-from $IMAGE:latest --tag "$IMAGE:$TAG" --tag "$IMAGE:latest" --build-arg JVM_TAG=$JVM_TAG --build-arg JMX_EXPORTER_VERSION=$JMX_EXPORTER_VERSION -f scripts/docker/Dockerfile .
    - docker push "$IMAGE:$TAG"
    - docker push "$IMAGE:latest"
  cache:
    policy: pull
  only:
    - /^rel\//
  except:
    - branches
  tags:
    - docker
