---

version: "3.7"
services:

  startrek:
    image: startrek:latest
    ports:
      - "8080:8080"
    environment:
      RUN_OPTS: "local"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: startrek
      POSTGRES_USER: theborg
      POSTGRES_PASSWORD: resistanceisfutile
