--

CREATE TABLE IF NOT EXISTS starship (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    captain text,
    affiliation text,
    launched smallint,
    class text,
    registry text,
    image text
);

INSERT INTO starship (captain, affiliation, launched, class, registry, image) VALUES
('Jonathan Archer', 'United Federation of Planets', 2151, 'NX', 'NX-01', 'nx01.jpg'),
('James T. Kirk', 'United Federation of Planets', 2245, 'Constitution', 'NCC-1701', 'ncc1701.jpg'),
('James T. Kirk', 'United Federation of Planets', 2286, 'Constitution', 'NCC-1701-A', 'ncc1701-a.jpg'),
('John Harriman', 'United Federation of Planets', 2293, 'Constitution', 'NCC-1701-B', 'ncc1701-b.jpg'),
('Rachel Garrett', 'United Federation of Planets', 2332, 'Constitution', 'NCC-1701-C', 'ncc1701-c.jpg'),
('Jean-Luc Picard', 'United Federation of Planets', 2363, 'Constitution', 'NCC-1701-D', 'ncc1701-d.jpg'),
('Jean-Luc Picard', 'United Federation of Planets', 2372, 'Constitution', 'NCC-1701-E', 'ncc1701-e.jpg');
